### PR TITLE
Unit test for getBookDetailById

### PR DESCRIPTION
**Pull request by younghyunlee22**

### CODE REVIEW

**Comment by hunjoonrhee** [comment]
It would be great if we had a test case for when no book was found and an error message appeared saying there is no book for the ID (or something similar).

At the moment, in my opinion, we have dealt with a general error case. What do you think about this?

**Review by hunjoonrhee — CHANGES_REQUESTED** [review]
maybe one tast case more for book not found ?

**Review by MayHyeyeonKim — APPROVED** [review]
whan jeon mut zeo yo!!

**Comment by Joel-Hwang** [comment]
LGTM (Looks good to me)

**Review by Joel-Hwang — APPROVED** [review]
LGTM (Looks good to me)

**Comment by younghyunlee22** [comment]
> maybe one tast case more for book not found ?

It has been added. https://github.com/BookDo7starsTS/bookdo7stars_be/pull/13/commits/7e6f0c7702b634fc21740323de11d5196a1265e7

**Pull request closed without merging**
